apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-backup
spec:
  template:
    spec:
      containers:
      - name: mongodb-backup
        image: bitnami/mongodb:latest
        command: ["/bin/bash", "-c"]
        args: ["/scripts/backup-mongodb.sh"]
        volumeMounts:
        - name: backup-script
          mountPath: /scripts
        - name: backup-storage
          mountPath: /backup
      restartPolicy: OnFailure
      volumes:
      - name: backup-script
        configMap:
          name: mongodb-backup-script
      - name: backup-storage
        persistentVolumeClaim:
          claimName: mongodb-backup-pvc