apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-backup-script
data:
  backup-mongodb.sh: |
    #!/bin/bash
    set -e

    MONGODB_HOST="my-mongodb-mongodb.default.svc.cluster.local"
    MONGODB_PORT=27017
    BACKUP_DIR="/backup"
    TIMESTAMP=$(date +%F_%T)

    mkdir -p ${BACKUP_DIR}

    mongodump --host ${MONGODB_HOST}:${MONGODB_PORT} --out ${BACKUP_DIR}/backup-${TIMESTAMP}

    tar -czvf ${BACKUP_DIR}/backup-${TIMESTAMP}.tar.gz -C ${BACKUP_DIR} backup-${TIMESTAMP}

    rm -rf ${BACKUP_DIR}/backup-${TIMESTAMP}