apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-restore-script
data:
  restore-mongodb.sh: |
    #!/bin/bash
    set -e

    MONGODB_HOST="my-mongodb-mongodb.default.svc.cluster.local"
    MONGODB_PORT=27017
    BACKUP_DIR="/backup"
    BACKUP_FILE=${BACKUP_DIR}/backup-$1.tar.gz

    tar -xzvf ${BACKUP_FILE} -C ${BACKUP_DIR}

    mongorestore --host ${MONGODB_HOST}:${MONGODB_PORT} --dir ${BACKUP_DIR}/backup-$1

    rm -rf ${BACKUP_DIR}/backup-$1