apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: rocketchat
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb